FROM node:12

# Update npm
RUN npm i -g npm

WORKDIR /app/

ADD config/services/frontend/app/package.json /app/package.json
ADD config/services/frontend/app/package-lock.json /app/package-lock.json
ADD config/services/frontend/app/config /app/config

RUN npm install

CMD npm run watch
